// Исходные данные для списка.
import {IListItemData} from './ListMasterFull';
import {EMarkerStatus} from '@sberbusiness/triplex/components/Marker/enums';

// Статусы элементов списка. По ним происходит фильтр.
export enum EListItemStatus {
    Sozdan = 'Sozdan',
    OshibkaKontrolja = 'OshibkaKontrolja',
    Otozvan = 'Otozvan',
    ZaproshenOtzyv = 'ZaproshenOtzyv',
    Importirovan = 'Importirovan',
    Podpisan = 'Podpisan',
}

const listItemsData: IListItemData[] = [
    {
        amount: 200,
        description: 'В том числе НДС 20 % - 33 рубля.',
        id: 'listmaster-list-item-1',
        numberAndDate: '№ 930109 от 08.08.2024',
        status: EListItemStatus.Sozdan,
        statusMarker: EMarkerStatus.WAITING,
        statusText: 'Создан',
        title: 'ООО "Теплые руки"',
    },
    {
        amount: 300,
        description: 'НДС не облагается.',
        id: 'listmaster-list-item-2',
        numberAndDate: '№ 930108 от 08.08.2024',
        status: EListItemStatus.OshibkaKontrolja,
        statusMarker: EMarkerStatus.WARNING,
        statusText: 'Ошибка контроля',
        title: 'АОЗТ "БЮДЖЕТ"',
    },
    {
        amount: 300,
        description: 'НДС не облагается.',
        id: 'listmaster-list-item-3',
        numberAndDate: '№ 930107 от 08.08.2024',
        status: EListItemStatus.OshibkaKontrolja,
        statusMarker: EMarkerStatus.WARNING,
        statusText: 'Ошибка контроля',
        title: 'АОЗТ "БЮДЖЕТ"',
    },
    {
        amount: 300,
        description: 'НДС не облагается.',
        id: 'listmaster-list-item-4',
        numberAndDate: '№ 930106 от 08.08.2024',
        status: EListItemStatus.Sozdan,
        statusMarker: EMarkerStatus.WAITING,
        statusText: 'Создан',
        title: 'АОЗТ "БЮДЖЕТ"',
    },
    {
        amount: 111,
        description: 'В том числе НДС 20 % - 18.50 рублей.',
        id: 'listmaster-list-item-5',
        numberAndDate: '№ 930105 от 08.08.2024',
        status: EListItemStatus.Sozdan,
        statusMarker: EMarkerStatus.WAITING,
        statusText: 'Создан',
        title: 'ООО "АТОМ"',
    },
    {
        amount: 2,
        description: 'В том числе НДС 20 % - 0.33 рублей.',
        id: 'listmaster-list-item-6',
        numberAndDate: '№ 930104 от 08.08.2024',
        status: EListItemStatus.Sozdan,
        statusMarker: EMarkerStatus.WAITING,
        statusText: 'Создан',
        title: 'ООО "Теплые руки"',
    },
    {
        amount: 10,
        description: 'INTV-T494 [JUnit] В том числе НДС 20 % - 5 рублей.',
        id: 'listmaster-list-item-7',
        numberAndDate: '№ 929573 от 07.08.2024',
        status: EListItemStatus.OshibkaKontrolja,
        statusMarker: EMarkerStatus.WARNING,
        statusText: 'Ошибка контроля',
        title: 'OOO "Vegas"',
    },
    {
        amount: 490,
        description: 'INTV-T494 [JUnit] В том числе НДС 20 % - 120 рублей.',
        id: 'listmaster-list-item-8',
        numberAndDate: '№ 930103 от 07.08.2024',
        status: EListItemStatus.Otozvan,
        statusMarker: EMarkerStatus.ERROR,
        statusText: 'Отозван',
        title: 'OOO "Vegas"',
    },
    {
        amount: 310,
        description: 'INTV-T494 [JUnit] В том числе НДС 20 % - 60 рублей.',
        id: 'listmaster-list-item-9',
        numberAndDate: '№ 930102 от 07.08.2024',
        status: EListItemStatus.ZaproshenOtzyv,
        statusMarker: EMarkerStatus.WAITING,
        statusText: 'Запрошен отзыв',
        title: 'OOO "Vegas"',
    },
    {
        amount: 272,
        description: 'INTV-T494 [JUnit] В том числе НДС 20 % - 54 рубля.',
        id: 'listmaster-list-item-10',
        numberAndDate: '№ 930101 от 07.08.2024',
        status: EListItemStatus.ZaproshenOtzyv,
        statusMarker: EMarkerStatus.WAITING,
        statusText: 'Запрошен отзыв',
        title: 'OOO "Vegas"',
    },
    {
        amount: 387,
        description: 'INTV-T494 [JUnit] В том числе НДС 20 % - 98 рублей.',
        id: 'listmaster-list-item-11',
        numberAndDate: '№ 930100 от 07.08.2024',
        status: EListItemStatus.Importirovan,
        statusMarker: EMarkerStatus.WAITING,
        statusText: 'Импортирован',
        title: 'OOO "Vegas"',
    },
    {
        amount: 425,
        description: 'INTV-T494 [JUnit] В том числе НДС 20 % - 187 рублей.',
        id: 'listmaster-list-item-12',
        numberAndDate: '№ 930200 от 07.08.2024',
        status: EListItemStatus.Sozdan,
        statusMarker: EMarkerStatus.WAITING,
        statusText: 'Создан',
        title: 'OOO "Vegas"',
    },
    {
        amount: 125,
        description: 'INTV-T494 [JUnit] В том числе НДС 20 % - 87 рублей.',
        id: 'listmaster-list-item-13',
        numberAndDate: '№ 930099 от 07.08.2024',
        status: EListItemStatus.Podpisan,
        statusMarker: EMarkerStatus.WAITING,
        statusText: 'Подписан',
        title: 'OOO "Vegas"',
    },
    {
        amount: 163,
        description: 'INTV-T494 [JUnit] В том числе НДС 20 % - 87 рублей.',
        id: 'listmaster-list-item-14',
        numberAndDate: '№ 930098 от 07.08.2024',
        status: EListItemStatus.OshibkaKontrolja,
        statusMarker: EMarkerStatus.WARNING,
        statusText: 'Ошибка контроля',
        title: 'OOO "Vegas"',
    },
    {
        amount: 323,
        description: 'INTV-T494 [JUnit] В том числе НДС 20 % - 105 рублей.',
        id: 'listmaster-list-item-15',
        numberAndDate: '№ 930097 от 07.08.2024',
        status: EListItemStatus.Podpisan,
        statusMarker: EMarkerStatus.WAITING,
        statusText: 'Подписан',
        title: 'OOO "Vegas"',
    },
    {
        amount: 175,
        description: 'INTV-T494 [JUnit] В том числе НДС 20 % - 87 рублей.',
        id: 'listmaster-list-item-16',
        numberAndDate: '№ 930096 от 07.08.2024',
        status: EListItemStatus.Sozdan,
        statusMarker: EMarkerStatus.WAITING,
        statusText: 'Создан',
        title: 'OOO "Vegas"',
    },
    {
        amount: 282,
        description: 'INTV-T494 [JUnit] В том числе НДС 20 % - 87 рублей.',
        id: 'listmaster-list-item-17',
        numberAndDate: '№ 930095 от 07.08.2024',
        status: EListItemStatus.Sozdan,
        statusMarker: EMarkerStatus.WAITING,
        statusText: 'Создан',
        title: 'OOO "Vegas"',
    },
    {
        amount: 469,
        description: 'INTV-T494 [JUnit] В том числе НДС 20 % - 125 рублей.',
        id: 'listmaster-list-item-18',
        numberAndDate: '№ 930094 от 07.08.2024',
        status: EListItemStatus.OshibkaKontrolja,
        statusMarker: EMarkerStatus.WARNING,
        statusText: 'Ошибка контроля',
        title: 'OOO "Vegas"',
    },
    {
        amount: 469,
        description: 'INTV-T494 [JUnit] В том числе НДС 20 % - 125 рублей.',
        id: 'listmaster-list-item-19',
        numberAndDate: '№ 930194 от 07.08.2024',
        status: EListItemStatus.Sozdan,
        statusMarker: EMarkerStatus.WAITING,
        statusText: 'Создан',
        title: 'OOO "Vegas"',
    },
    {
        amount: 191,
        description: 'INTV-T494 [JUnit] В том числе НДС 20 % - 55 рублей.',
        id: 'listmaster-list-item-20',
        numberAndDate: '№ 930093 от 07.08.2024',
        status: EListItemStatus.Sozdan,
        statusMarker: EMarkerStatus.WAITING,
        statusText: 'Создан',
        title: 'OOO "Vegas"',
    },
    {
        amount: 248,
        description: 'INTV-T494 [JUnit] В том числе НДС 20 % - 66 рублей.',
        id: 'listmaster-list-item-21',
        numberAndDate: '№ 930082 от 07.08.2024',
        status: EListItemStatus.Sozdan,
        statusMarker: EMarkerStatus.WAITING,
        statusText: 'Создан',
        title: 'OOO "Vegas"',
    },
    {
        amount: 272,
        description: 'INTV-T494 [JUnit] В том числе НДС 20 % - 66 рублей.',
        id: 'listmaster-list-item-22',
        numberAndDate: '№ 930079 от 07.08.2024',
        status: EListItemStatus.Sozdan,
        statusMarker: EMarkerStatus.WAITING,
        statusText: 'Создан',
        title: 'OOO "Vegas"',
    },
    {
        amount: 435,
        description: 'INTV-T2524 [JUnit] В том числе НДС 20 % - 87 рублей.',
        id: 'listmaster-list-item-23',
        numberAndDate: '№ 930078 от 07.08.2024',
        status: EListItemStatus.Importirovan,
        statusMarker: EMarkerStatus.WAITING,
        statusText: 'Импортирован',
        title: 'МЕЖРАЙОННАЯ ИФНС РОССИИ № 1 ПО РЯЗАНСКОЙ ОБЛАСТИ',
    },
    {
        amount: 181,
        description: 'INTV-T2524 [JUnit] В том числе НДС 20 % - 87 рублей.',
        id: 'listmaster-list-item-24',
        numberAndDate: '№ 930077 от 07.08.2024',
        status: EListItemStatus.Importirovan,
        statusMarker: EMarkerStatus.WAITING,
        statusText: 'Импортирован',
        title: 'МЕЖРАЙОННАЯ ИФНС РОССИИ № 1 ПО РЯЗАНСКОЙ ОБЛАСТИ',
    },
];

export default listItemsData;
