// Токены компонентов.
import {TDesignTokensComponents} from '@sberbusiness/triplex/components/DesignTokens/types/DesignTokensTypes';
import {ETriplexTheme} from '@sberbusiness/triplex/components/ThemeProvider/ETriplexTheme';
import {GetTokensValueByTheme} from '@sberbusiness/triplex/components/DesignTokens/GetTokensValueByTheme';
import {
    AccordionForm_Tokens,
    AccordionView_Tokens,
    AlertContext_Tokens,
    AlertProcess_Tokens,
    Body_Tokens,
    Button_Tokens,
    Calendar_Tokens,
    Card_Tokens,
    Checkbox_Tokens,
    Confirm_Tokens,
    Divider_Tokens,
    Dropdown_Tokens,
    DropdownList_Tokens,
    Footer_Tokens,
    FormField_Tokens,
    Header_Tokens,
    Input_Tokens,
    Label_Tokens,
    LightBox_Tokens,
    Link_Tokens,
    Marker_Tokens,
    MarkerStatus_Tokens,
    Multiselect_Tokens,
    Notification_Tokens,
    Radio_Tokens,
    SegmentedControl_Tokens,
    Select_Tokens,
    Skeleton_Tokens,
    Slider_LM,
    SmallInput_Tokens,
    SMSInput_Tokens,
    Spinner_Tokens,
    Spoiler_Tokens,
    Stepper_Tokens,
    TableBasic_Tokens,
    Tabs_Tokens,
    TabsFolder_Tokens,
    Tag_Tokens,
    Text_Tokens,
    Title_Tokens,
    Tooltip_Tokens,
    TopOverlay_Tokens,
    UnorderedList_Tokens,
    UploadZone_Tokens,
    Widget_Tokens,
    TDesignTokensComponentsAccordionFormValue,
    TDesignTokensComponentsAccordionViewValue,
    TDesignTokensComponentsAlertContextValue,
    TDesignTokensComponentsAlertProcessValue,
    TDesignTokensComponentsBodyValue,
    TDesignTokensComponentsButtonValue,
    TDesignTokensComponentsCalendarValue,
    TDesignTokensComponentsCardValue,
    TDesignTokensComponentsCheckboxValue,
    TDesignTokensComponentsConfirmValue,
    TDesignTokensComponentsDividerValue,
    TDesignTokensComponentsDropdownListValue,
    TDesignTokensComponentsDropdownValue,
    TDesignTokensComponentsFooterValue,
    TDesignTokensComponentsFormFieldValue,
    TDesignTokensComponentsHeaderValue,
    TDesignTokensComponentsInputValue,
    TDesignTokensComponentsLabelValue,
    TDesignTokensComponentsLightBoxValue,
    TDesignTokensComponentsLinkValue,
    TDesignTokensComponentsMarkerValue,
    TDesignTokensComponentsMarkerStatusValue,
    TDesignTokensComponentsMultiselectValue,
    TDesignTokensComponentsNotificationValue,
    TDesignTokensComponentsRadioValue,
    TDesignTokensComponentsSegmentedControlValue,
    TDesignTokensComponentsSelectValue,
    TDesignTokensComponentsSkeletonValue,
    TDesignTokensComponentsSmallInputValue,
    TDesignTokensComponentsSMSInputValue,
    TDesignTokensComponentsSpinnerValue,
    TDesignTokensComponentsSpoilerValue,
    TDesignTokensComponentsStepperValue,
    TDesignTokensComponentsTableBasicValue,
    TDesignTokensComponentsTabsValue,
    TDesignTokensComponentsTabsFolderValue,
    TDesignTokensComponentsTagValue,
    TDesignTokensComponentsTextValue,
    TDesignTokensComponentsTitleValue,
    TDesignTokensComponentsTooltipValue,
    TDesignTokensComponentsTopOverlayValue,
    TDesignTokensComponentsUnorderedListValue,
    TDesignTokensComponentsUploadZoneValue,
    TDesignTokensComponentsWidgetValue,
} from '@sberbusiness/triplex/components/DesignTokens/components';

export const DesignTokensComponents: TDesignTokensComponents = {
    AccordionForm: GetTokensValueByTheme<TDesignTokensComponentsAccordionFormValue>(ETriplexTheme.LIGHT, AccordionForm_Tokens),
    AccordionView: GetTokensValueByTheme<TDesignTokensComponentsAccordionViewValue>(ETriplexTheme.LIGHT, AccordionView_Tokens),
    AlertContext: GetTokensValueByTheme<TDesignTokensComponentsAlertContextValue>(ETriplexTheme.LIGHT, AlertContext_Tokens),
    AlertProcess: GetTokensValueByTheme<TDesignTokensComponentsAlertProcessValue>(ETriplexTheme.LIGHT, AlertProcess_Tokens),
    backdrop: {
        background: {
            value: 'rgba(31, 31, 34, 0.56)', //     var(--triplex-backdrop-background)
        },
    },
    Body: GetTokensValueByTheme<TDesignTokensComponentsBodyValue>(ETriplexTheme.LIGHT, Body_Tokens),
    Button: GetTokensValueByTheme<TDesignTokensComponentsButtonValue>(ETriplexTheme.LIGHT, Button_Tokens),
    Calendar: GetTokensValueByTheme<TDesignTokensComponentsCalendarValue>(ETriplexTheme.LIGHT, Calendar_Tokens),
    Card: GetTokensValueByTheme<TDesignTokensComponentsCardValue>(ETriplexTheme.LIGHT, Card_Tokens),
    Checkbox: GetTokensValueByTheme<TDesignTokensComponentsCheckboxValue>(ETriplexTheme.LIGHT, Checkbox_Tokens),
    Confirm: GetTokensValueByTheme<TDesignTokensComponentsConfirmValue>(ETriplexTheme.LIGHT, Confirm_Tokens),
    Divider: GetTokensValueByTheme<TDesignTokensComponentsDividerValue>(ETriplexTheme.LIGHT, Divider_Tokens),
    Dropdown: GetTokensValueByTheme<TDesignTokensComponentsDropdownValue>(ETriplexTheme.LIGHT, Dropdown_Tokens),
    DropdownList: GetTokensValueByTheme<TDesignTokensComponentsDropdownListValue>(ETriplexTheme.LIGHT, DropdownList_Tokens),
    Footer: GetTokensValueByTheme<TDesignTokensComponentsFooterValue>(ETriplexTheme.LIGHT, Footer_Tokens),
    FormField: GetTokensValueByTheme<TDesignTokensComponentsFormFieldValue>(ETriplexTheme.LIGHT, FormField_Tokens),
    Header: GetTokensValueByTheme<TDesignTokensComponentsHeaderValue>(ETriplexTheme.LIGHT, Header_Tokens),
    Input: GetTokensValueByTheme<TDesignTokensComponentsInputValue>(ETriplexTheme.LIGHT, Input_Tokens),
    Label: GetTokensValueByTheme<TDesignTokensComponentsLabelValue>(ETriplexTheme.LIGHT, Label_Tokens),
    LightBox: GetTokensValueByTheme<TDesignTokensComponentsLightBoxValue>(ETriplexTheme.LIGHT, LightBox_Tokens),
    Link: GetTokensValueByTheme<TDesignTokensComponentsLinkValue>(ETriplexTheme.LIGHT, Link_Tokens),
    Marker: GetTokensValueByTheme<TDesignTokensComponentsMarkerValue>(ETriplexTheme.LIGHT, Marker_Tokens),
    MarkerStatus: GetTokensValueByTheme<TDesignTokensComponentsMarkerStatusValue>(ETriplexTheme.LIGHT, MarkerStatus_Tokens),
    Multiselect: GetTokensValueByTheme<TDesignTokensComponentsMultiselectValue>(ETriplexTheme.LIGHT, Multiselect_Tokens),
    Notification: GetTokensValueByTheme<TDesignTokensComponentsNotificationValue>(ETriplexTheme.LIGHT, Notification_Tokens),
    overlay: {
        maskBackground: {
            value: 'rgba(255, 255, 255, 0.8)', //     var(--triplex-overlay-maskBackground)
        },
    },
    Radio: GetTokensValueByTheme<TDesignTokensComponentsRadioValue>(ETriplexTheme.LIGHT, Radio_Tokens),
    SegmentedControl: GetTokensValueByTheme<TDesignTokensComponentsSegmentedControlValue>(ETriplexTheme.LIGHT, SegmentedControl_Tokens),
    Select: GetTokensValueByTheme<TDesignTokensComponentsSelectValue>(ETriplexTheme.LIGHT, Select_Tokens),
    Skeleton: GetTokensValueByTheme<TDesignTokensComponentsSkeletonValue>(ETriplexTheme.LIGHT, Skeleton_Tokens),
    Slider: Slider_LM,
    SmallInput: GetTokensValueByTheme<TDesignTokensComponentsSmallInputValue>(ETriplexTheme.LIGHT, SmallInput_Tokens),
    SMSInput: GetTokensValueByTheme<TDesignTokensComponentsSMSInputValue>(ETriplexTheme.LIGHT, SMSInput_Tokens),
    Spinner: GetTokensValueByTheme<TDesignTokensComponentsSpinnerValue>(ETriplexTheme.LIGHT, Spinner_Tokens),
    Spoiler: GetTokensValueByTheme<TDesignTokensComponentsSpoilerValue>(ETriplexTheme.LIGHT, Spoiler_Tokens),
    Stepper: GetTokensValueByTheme<TDesignTokensComponentsStepperValue>(ETriplexTheme.LIGHT, Stepper_Tokens),
    TableBasic: GetTokensValueByTheme<TDesignTokensComponentsTableBasicValue>(ETriplexTheme.LIGHT, TableBasic_Tokens),
    Tabs: GetTokensValueByTheme<TDesignTokensComponentsTabsValue>(ETriplexTheme.LIGHT, Tabs_Tokens),
    TabsFolder: GetTokensValueByTheme<TDesignTokensComponentsTabsFolderValue>(ETriplexTheme.LIGHT, TabsFolder_Tokens),
    Tag: GetTokensValueByTheme<TDesignTokensComponentsTagValue>(ETriplexTheme.LIGHT, Tag_Tokens),
    Text: GetTokensValueByTheme<TDesignTokensComponentsTextValue>(ETriplexTheme.LIGHT, Text_Tokens),
    Title: GetTokensValueByTheme<TDesignTokensComponentsTitleValue>(ETriplexTheme.LIGHT, Title_Tokens),
    Tooltip: GetTokensValueByTheme<TDesignTokensComponentsTooltipValue>(ETriplexTheme.LIGHT, Tooltip_Tokens),
    TopOverlay: GetTokensValueByTheme<TDesignTokensComponentsTopOverlayValue>(ETriplexTheme.LIGHT, TopOverlay_Tokens),
    UnorderedList: GetTokensValueByTheme<TDesignTokensComponentsUnorderedListValue>(ETriplexTheme.LIGHT, UnorderedList_Tokens),
    UploadZone: GetTokensValueByTheme<TDesignTokensComponentsUploadZoneValue>(ETriplexTheme.LIGHT, UploadZone_Tokens),
    Widget: GetTokensValueByTheme<TDesignTokensComponentsWidgetValue>(ETriplexTheme.LIGHT, Widget_Tokens),
};
