# This is a basic workflow to help you get started with Actions

name: Styleguidist Deploy

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      pkgVersion:
        type: string
        description: 'Версия пакета (10.0.2)'
        required: true

      standPopt:
        type: string
        description: 'Порт в формате 5.XX.Y.Z, где 1 - константа, XX - номер версии мажор, Y - номер версии минор, Z - номер версии патч. Пример для версии 10.0.2 => 51002'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.TRIPLEX_DOCKER_REGISTRY_URL }}
          username: ${{ secrets.TRIPLEX_DOCKER_REGISTRY_USER }}
          password: ${{ secrets.TRIPLEX_DOCKER_REGISTRY_USER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            ${{ secrets.TRIPLEX_DOCKER_REGISTRY_URL }}/styleguidist-${{ github.event.inputs.pkgVersion }}

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TRIPLEX_STYLEGUIDE_HOST }}
          username: ${{ secrets.TRIPLEX_STYLEGUIDE_SSH_USER }}
          password: ${{ secrets.TRIPLEX_STYLEGUIDE_SSH_USER_PASSWORD }}
          script: |
            docker login https://${{ secrets.TRIPLEX_DOCKER_REGISTRY_URL }} -u ${{ secrets.TRIPLEX_DOCKER_REGISTRY_USER }} -p "${{ secrets.TRIPLEX_DOCKER_REGISTRY_USER_PASSWORD }}"
            docker rm -f styleguidist-${{ github.event.inputs.pkgVersion }} || true
            docker rmi ${{ secrets.TRIPLEX_DOCKER_REGISTRY_URL }}/styleguidist-${{ github.event.inputs.pkgVersion }} || true
            docker pull ${{ secrets.TRIPLEX_DOCKER_REGISTRY_URL }}/styleguidist-${{ github.event.inputs.pkgVersion }}
            docker run --rm -d --name styleguidist-${{ github.event.inputs.pkgVersion }} -p ${{ github.event.inputs.standPopt }}:80 ${{ secrets.TRIPLEX_DOCKER_REGISTRY_URL }}/styleguidist-${{ github.event.inputs.pkgVersion }}
            docker logout https://${{ secrets.TRIPLEX_DOCKER_REGISTRY_URL }}
