name: Publish

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 10.16.3

      - name: Publish
        run: |
          npm install
          npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
          npm run build-publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - uses: actions/upload-artifact@v2
        with:
          name: out
          path: out/
